namespace Assets.Scripts.StatusEffects
{
    public enum PlayerStatusEffectName
    {
        None,
        WeakRigidity,
        StrongRigidity,
        Down,
        Knockback,
        Airborne,
        KnockedAirborne,
        Stun,
        Confusion,
        Shock,
        Incarceration,
        Snare,
        Burn,
        Slowdown,
        Nearsight,
        Farsighted,
        Blind,
        Static,
        Adhesive,
        PowerUp,
        SpeedRacer,
        MuscleStrengthen,
        Marksman,
        Shield
    }
}